Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '3000'
    vb.cpus = '2'
  end

  config.vm.synced_folder "../../k8s", "/k8s",
    owner: "root", group: "root"
end