apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo02-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: environment, operator: NotIn, values: [dev]}