Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box = "k3s"
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '3000'
    vb.cpus = '2'
  end

  config.vm.provision 'shell',
    privileged: true,
    inline: 'curl -sfL https://get.k3s.io | sh -'

  config.vm.synced_folder "../../k8s", "/k8s",
    owner: "root", group: "root"
end