apiVersion: v1
kind: Pod
metadata:
  name: demo01
spec:
  containers:
    - name: test
      image: busybox
      command: ['sh', '-ec', 'sleep 3600']
      volumeMounts:
      - name: test-volume
        mountPath: /test
      resources:
  volumes:
  - name: test-volume
    emptyDir: {}